server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/App
    username: root
    password: Dph929502$
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates  #访问静态页面
mybatis:
  configuration:
    map-underscore-to-camel-case: true