server:
  port: 443
spring:
  datasource:
    url: jdbc:mysql://192.144.231.29:3306/app1
    username: root
    password: Dph929502$
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates  #访问静态页面
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: time